project:
  type: website
  execute-dir: project

website:
  title: "Mike O'Brien"
  navbar:
    background: primary
    left:
      - href: mailto:mikeob9@gmail.com
        icon: envelope
      - href: https://github.com/mhpob
        icon: github
      - href: https://twitter.com/ruggafish
        icon: twitter
      - file: spoil_land_park/find_parcels_view.qmd
        text: Interesting parcels
      - file: research/research_list.qmd
        text: Research

      

format:
  html:
    theme: lux
    css: styles.css
    toc: true



