project:
  type: website
  execute-dir: project

website:
  title: "Mike O'Brien"
  navbar:
    left:
      - href: spoil_land_park/find_parcels_view.qmd
        text: Interesting parcels
      - href: research/research_list.qmd
        text: Research
      

format:
  html:
    theme: lux
    css: styles.css
    toc: true



